<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFe98k9x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFe98k9x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFe98k9x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFe98k9x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFe98k9x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fe98k9x',
    'container.build_id' => '0120463f',
    'container.build_time' => 1523216251,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFe98k9x');
